# Generated by Django 3.1.7 on 2021-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpeoples',
            fields=[
                ('email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10)),
                ('profilepic', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
