# Generated by Django 3.1.7 on 2021-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cpeoples_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpeoples',
            name='profilepic',
            field=models.FileField(upload_to='cprofilepics/'),
        ),
    ]
