# Generated by Django 3.1.7 on 2021-04-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210318_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='capinitials',
            fields=[
                ('id', models.CharField(max_length=2500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('viewcount', models.IntegerField(default=0)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
