# Generated by Django 3.1.7 on 2021-04-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_auto_20210426_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='capinitials',
            fields=[
                ('id', models.CharField(max_length=2500, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=250, unique=True)),
                ('articename', models.CharField(max_length=250)),
                ('viewcount', models.IntegerField(default=0)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='cpeoples',
            fields=[
                ('fname', models.CharField(max_length=250, unique=True)),
                ('sname', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='userbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cpeoples')),
            ],
        ),
        migrations.CreateModel(
            name='user_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlename', models.CharField(max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cpeoples')),
            ],
        ),
    ]
