# Generated by Django 3.1.7 on 2021-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_capinitials_cpeoples_user_work_userbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capinitials',
            name='fname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cpeoples',
            name='fname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cpeoples',
            name='sname',
            field=models.CharField(max_length=250),
        ),
    ]
