# Generated by Django 3.1.7 on 2021-04-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210426_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='capinitials',
        ),
        migrations.RemoveField(
            model_name='user_work',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userbox',
            name='email',
        ),
        migrations.DeleteModel(
            name='cpeoples',
        ),
        migrations.DeleteModel(
            name='user_work',
        ),
        migrations.DeleteModel(
            name='userbox',
        ),
    ]
