# Generated by Django 3.1.7 on 2021-04-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_capinitials_cpeoples_user_work_userbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_work',
            old_name='articlename',
            new_name='articletopicname',
        ),
    ]
