# Generated by Django 3.1.7 on 2021-04-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210429_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='capinitials',
        ),
        migrations.RemoveField(
            model_name='user_work',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userbox',
            name='email',
        ),
        migrations.DeleteModel(
            name='cpeoples',
        ),
        migrations.DeleteModel(
            name='user_work',
        ),
        migrations.DeleteModel(
            name='userbox',
        ),
    ]
