# Generated by Django 3.1.7 on 2021-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_capinitials_cpeoples_user_work_userbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_work',
            name='articleimagespath',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
